[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "bayesim"
version = "0.11.0"
license = "GPL-2.0-only"
dependencies = [
  "numpy>2.0",
  "scipy",
  "matplotlib",
  "joblib",
  "tables"
]